### ISSUE TITLE
allow message color override in settings

### ISSUE THREAD

**Issue by masterkain** [drone-plugins/drone-slack#102]
I use an initial step in my pipeline to send a message about a build that has just been started

```
steps:
  - name: slack-init
    image: plugins/slack
    settings:
      webhook: https://xxxx
      channel: deploy-feed
      template: "build just started"
```

however the message color seems to depend on the build status, which at this point I guess drone assumes it being green.

https://github.com/drone-plugins/drone-slack/blob/master/plugin.go#L94

it would be nice being able to send this message as `warning`:

https://github.com/drone-plugins/drone-slack/blob/master/plugin.go#L161

I suspect the default case might never be reached.
