### ISSUE TITLE
Commit message with quote ' converted to &apos;

### ISSUE THREAD

**Issue by milhouse1337** [drone-plugins/drone-slack#105]
The `{{build.message}}` variable seems to be parsed for HTML entities. Is there a way to escape/truncate this ?

Here is an example commit message: 

> `Merge branch 'release/1.0.18'`

You will receive this in Slack:

> `Merge branch &apos;release/1.0.18&apos;`

Using the following config:

```yaml
- name: notify
  image: plugins/slack
  settings:
    webhook: { from_secret: ... }
    channel: test
    template: |
      Build #{{build.number}} completed in {{since build.created}}.
      > {{build.message}}
```

![Example](https://i.imgur.com/8va6Er8.png)

The Slack doc says the following characters are reserved as characters for formatting `&`, `<`, and `>`. Everything else should be parsed as is (literal) I think.

https://api.slack.com/reference/surfaces/formatting

Thank you for this awesome project btw! 🚀
