### ISSUE TITLE
Newlines not working in message template

### ISSUE THREAD

**Issue by jemaltieri** [drone-plugins/drone-slack#113]
Given this step:
```
    - name: repro for github issue
      image: plugins/slack
      settings:
        webhook:
          from_secret: slack_deploy_notifications_webhook
        channel: deploy-notifications
        template: >
          this is a line\n
          this should be a new line
```
The message that is displayed in slack is:
> this is a line\n this should be a new line
<img width="350" alt="Screen Shot 2020-10-23 at 12 33 02 PM" src="https://user-images.githubusercontent.com/273548/97029839-f69a0c80-152b-11eb-9100-c8187bd0dbf9.png">

Expected result is:
>>> this is a line
this is a new line
