### ISSUE TITLE
Only send notifications on if one of a set of specific steps fails

### ISSUE THREAD

**Issue by foosinn** [drone-plugins/drone-slack#147]
Drone exposes the failed steps in `DRONE_FAILED_STEPS`.

Using this the extension could provide a very simply way to only alert if certain steps fail.

```yaml
  image: plugins/slack
  name: notify
  settings:
    webhook:
      from_secret: slack_webhook_url
    build_steps:
      - test
      - e2e-test
      - integration-test
  when:
    status:
    - failure
```
