### ISSUE TITLE
Drone doesn't link channel name

### ISSUE THREAD

**Issue by rstefan1** [drone-plugins/drone-slack#156]
Drone config:

```
name: TEST
  image: plugins/slack
  settings:
    webhook: ...
    channel: ...
    username: ...
    link_names: true
    template: >
      TEST <@channelname>
```

Message in slack without any link:

```
TEST @channelname
```
