### ISSUE TITLE
The plugin sends notifications as successful.

### ISSUE THREAD

**Issue by sviatoslav6** [drone-plugins/drone-slack#162]
The plugin sends notifications as successful, even when some steps in the pipeline have failed and resulted in an error.

My pipeline

```
kind: pipeline
type: kubernetes
name: test

trigger:
  branch:
    - master

clone:
  disable: true

steps:
  - name: test
    image: bitnami/git
    environment:
      SLACK_WEBHOOK:
        from_secret: SLACK_WEBHOOK
    commands:
      - kubectl get pod
    when:
      event: [push]

  - name: slack-notify
    image: plugins/slack
    environment:
      SLACK_WEBHOOK:
        from_secret: SLACK_WEBHOOK
    settings:
      webhook: $${SLACK_WEBHOOK}
      channel: my-channel
      template: >

        {{#success build.status}} ✔ {{ else }} :x: {{/success}} {{ uppercasefirst build.status }}: Build #{{ build.number }} * (type: `{{ build.event }}`)

        Repository:  <https://github.com/{{ repo.name }}>

        Commit: <https://github.com/{{ repo.owner }}/{{ repo.name }}/commit/{{ build.commit }}|{{ truncate build.commit 8 }}>

        Branch: <https://github.com/{{ repo.owner }}/{{ repo.name }}/commits/{{ build.branch }}|{{ build.branch }}>

        Author: {{ build.author }}

        Build: <{{ build.link }}| Drone Build {{ build.number }} ↗>
    when:
      event: [push]
      status: [success, failure]
      branch: [master]
    depends_on:
      - test
```
step test ends with an error, because no such command 

![image](https://github.com/drone-plugins/drone-slack/assets/106230100/63cefc38-2b71-48db-a329-c1f17bbd1297)

in the slack message that the build was successful

![image](https://github.com/drone-plugins/drone-slack/assets/106230100/e1370e08-da5f-4c35-aa7d-09aba18793b0)
