### ISSUE TITLE
More powerful templates

### ISSUE THREAD

**Issue by ProLoser** [drone-plugins/drone-slack#31]
I tried creating a custom template as follows:

```
notify:
  slack:
    webhook_url: ...
    channel: ...
    username: "New Release"
    on_success: true
    on_failure: true
    template: >
      Project: *<https://github.com/{{ repo.owner }}/{{ repo.name }}|{{ repo.name }}>* \n
      Version: *<https://github.com/{{ repo.owner }}/{{ repo.name }}/tree/{{ build.commit }}|{{ build.branch }}>* \n
      Author: *<https://github.com/{{ repo.owner }}/{{ repo.name }}/commit/{{ build.commit }}|{{ build.author }}>* \n
      Status: *<{{ sys.link }}|{{ build.status }}>*
```

There were a few problems:
1. `sys.link` was empty
2. It would have been nice if I could have extracted the tag from the `build.branch` similar to how [you extract the first 8 characters](https://github.com/drone-plugins/drone-slack/blob/release/0.4/main.go#L108) from `build.commit`
