### ISSUE TITLE
412460h15m1s 

### ISSUE THREAD

**Issue by nemonik** [drone-plugins/drone-slack#40]
For use w/ Drone v0.5 and the following as part of pipeline:

```
  slack:
    image: plugins/slack
    webhook: https://hooks.slack.com/services/[snip]
    username: drone
    channel: chatops
    template: >
      *{{ build.status }}* {{ repo.name }}#{{ build.tag }} ({{ build.branch }}) by {{ build.author }} time spent {{since build.started}}
```

The duration between now and the start of build is reported as `412460h15m1s`.

Yikes.  That ain't right.
