### ISSUE TITLE
Post : unsupported protocol scheme ""

### ISSUE THREAD

**Issue by tonymadbrain** [drone-plugins/drone-slack#47]
Hello, I have this lines in .drone.yml:
```
notify:
    image: plugins/slack
    webhook_url: https://hooks.slack.com/services/xxx/yyy/zzz
    channel: drone
```
and getting this in job:
![screenshot_20170324172557](https://cloud.githubusercontent.com/assets/5266592/24298424/06ec47a6-10b7-11e7-8417-4f3f0585eef9.png)
