### ISSUE TITLE
icon_url is ignored

### ISSUE THREAD

**Issue by daniel-ac-martin** [drone-plugins/drone-slack#52]
It would appear the setting `icon_url` has no effect.

**Comment by bradrydzewski** [comment]
I just tested the below configuration and it used a custom icon url as expected

```
pipeline:
  slack:
    image: plugins/slack
    icon_url: https://slack.global.ssl.fastly.net/9fa2/img/services/hubot_128.png
```
