### ISSUE TITLE
Not compatible with 0.6?

### ISSUE THREAD

**Issue by vespakoen** [drone-plugins/drone-slack#53]
Hey there!

I haven't worked with drone in a while, and now picked it up again, I took some of my 0.5 configs and turned them to 0.6, now my build are always reported as successful in slack, even though the build fails (also shows red in the web interface).

I tried with a template, but I got the same results, adding {{build.status}} to the template shows `success`.

Perhaps it is reporting the status of itself? (The "notify" step in the following image is the slack plugin)

<img width="512" alt="screen shot 2017-05-05 at 17 06 49" src="https://cloud.githubusercontent.com/assets/876117/25751450/56af606a-31b5-11e7-9e88-277ac8791870.png">

Here is my config:

```yaml
notify:
    image: plugins/slack:latest
    channel: ci
    secrets:
      - SLACK_WEBHOOK
    when:
      status: [ failure, success ]
    template: >
      {{#success build.status}}
        BOOM! build {{build.number}} succeeded (status: {{build.status}}). Good job.
      {{else}}
        NOPE! {{build.number}} failed. Fix me please...
      {{/success}}
```
