### ISSUE TITLE
Notify failing with slack plugin

### ISSUE THREAD

**Issue by vishal24tuniki** [drone-plugins/drone-slack#64]
Pipeline failing in notify when the event is Pull request with following error
`
Post : unsupported protocol scheme ""`

```
workspace:
  base: /go
  path: src/github.com/xxx/xxx

pipeline:
  backend:
    image: golang:1.8.3
    commands:
      - go get github.com/tools/godep
      - go get -d ./...
      - godep restore ./...
      - export GOBIN=$GOPATH/bin
      - go vet ./...
      - go install

  notify:
    image: plugins/slack
    secrets: [ slack_webhook ]
    when:
      status: [ success, failure ]
    template: >
      {{#success build.status}}
        {{repo.name}} ({{build.branch}}) <{{ build.link }}|{{ repo.owner }}/{{ repo.name }}#{{truncate build.commit 8}}> build succeeded on {{uppercasefirst build.event}}. Good job {{ build.author }}.
      {{else}}
        {{repo.name}} ({{build.branch}}) <{{ build.link }}|{{ repo.owner }}/{{ repo.name }}#{{truncate build.commit 8}}> build failed on {{uppercasefirst build.event}}. Fix me please {{ build.author }}.
      {{/success}}


```
