### ISSUE TITLE
Bad link to the build

### ISSUE THREAD

**Issue by maximelebastard** [drone-plugins/drone-slack#75]
Hi,

Here is my plugin call:

```yaml
pipeline:
  slack:
    image: plugins/slack
    secrets: [slack_webhook]
    username: drone
    when:
      status: [failure]
```

And the docker-compose.yml that runs docker:
```yaml
services:

#... Nginx reverse proxy configuration ...

drone-server:
    image: drone/drone:0.8
    volumes:
      - ${DRONE_DATA_DIR}:/var/lib/drone/
      - ./.drone-env.yml:/etc/drone-env.yml
    restart: always
    environment:
      - DRONE_OPEN=${DRONE_OPEN}
      - DRONE_ORGS=${DRONE_ORGS}
      - DRONE_ADMIN=${DRONE_ADMIN}
      - DRONE_HOST=${DRONE_HOST} #=https://ci.mycompany.com
      - DRONE_BITBUCKET=true
      - DRONE_BITBUCKET_CLIENT=${DRONE_BITBUCKET_CLIENT}
      - DRONE_BITBUCKET_SECRET=${DRONE_BITBUCKET_SECRET}
      - DRONE_SECRET=${DRONE_SECRET}
  drone-agent-one:
    image: drone/agent:0.8
    command: agent
    restart: always
    depends_on:
      - drone-server
    volumes:
      - ${DOCKER_HOST_SOCKET}:/var/run/docker.sock
    environment:
      - DRONE_SERVER=drone-server:${DRONE_AGENT_SERVER_PORT}
      - DRONE_SECRET=${DRONE_SECRET}
```

I get the notification on Slack, but when I click on the link, I land on ```http://drone-server:8000/mygroupname/myreponame/3``` when I'd like to land on ```https://ci.mycompany.com/mygroupname/myreponame/3```

As you can see in docker-compose.yml, my DRONE_HOST is defined. How is the link generated ? I don't master go very well 😉
