### ISSUE TITLE
Webhook as secret

### ISSUE THREAD

**Issue by matthax** [drone-plugins/drone-slack#81]
I am unable to pass the webhook variable in using a drone secret. Is there a custom configuration or documentation explaining this?

I have tried the usual formats:
```yaml
    webhook: $${SLACK_HOOK}
    webhook: $SLACK_HOOK
    secrets: [ SLACK_HOOK ]
```
etc.
