### ISSUE TITLE
secrets doesn't work when PR

### ISSUE THREAD

**Issue by tgly307** [drone-plugins/drone-slack#83]
I set notify part of pipeline like this:
```
notify:
    image: plugins/slack
    secrets: [ slack_webhook ]
    username: Test_Drone
    when:
      status: [ success, failure ]
```
it works when push, but it fails when PR, the error is `Post : unsupported protocol scheme ""`

Did I missed something? Or it is a bug?
