### ISSUE TITLE
Getting the slack username to tag on an unsuccessful build

### ISSUE THREAD

**Issue by srijeet0406** [drone-plugins/drone-slack#87]
Hello! I'm using the slack plugin in my drone pipeline to notify my channel on successful and unsuccessful builds. I was thinking of tagging the user on an unsuccessful build and sending a message on the channel when someone breaks the build. I'm having trouble figuring out how to use the slack username of the committer in my pipeline. I have a script, which makes a call to the salck API to get the slack name associated with that email. But I dont know how to access the output of this script in my nect step (which is the notify step). I'm writing the output of the script to a file, which I was trying to read in the "notify" script, but seems like we cannot add custom commands in the notify step? Here is my pipeline:

```
workspace:
  base: /go
  path: src/github.comcast.com/viper-ace/psn-router
  
pipeline:
  build:
    pull: true
    privileged: true
    image: registry.vipertv.net/viper-linear-routing/viper-drone-ci:0.0.0
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock
    commands:
      - make build
  find_user:
    privileged: true
    image: registry.vipertv.net/viper-linear-routing/viper-drone-ci:0.0.1
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock
    commands:
    - export tag_user=`./slack_api_request.sh`
    - echo "$tag_user" > ./tag_user

  notify:
    image: plugins/slack
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    channel: viper-leg-routing-ci
    link_names: true
    secrets: [ slack_webhook ]
    webhook: $SLACK_WEBHOOK
    template: >
      {{#failure build.status}}
        BUILD BROKEN! <@THIS IS WHERE I WOULD LIKE TO GET THE SLACK USERNAME>
      {{else}}
        YAY!! BUILD PASSED!
      {{/failure}}
    when:
      event: [ push, tag, deployment, pull_request ]
      status: [ success, failue ]
```

Any clue how to do this? :)
