### ISSUE TITLE
How do I use slack plugin within ssh pipeline

### ISSUE THREAD

**Issue by tintinthong** [drone-plugins/drone-slack#99]
Roughly code structure. 

```
kind: pipeline
type: ssh
name: default

server: 
    host: XXXX
    user: root
    ssh_key: 
        from_secret: ssh_key

steps: 
- name XXXX
...
...
...
- name: slack
  image: plugins/slack
  settings:
    webhook: XXXXXXXX
    channel: cicd
    template: > 
      {{#success build.status}} 
        *{{#success build.status}}✔{{ else }}✘{{/success}} {{ uppercasefirst build.status }}*: <https://github.com/{{ repo.owner }}/{{ repo.name }}/pull/{{ build.pull }}|Pull Request #{{ build.pull }}>
      {{else}}
        *{{#success build.status}}✔{{ else }}✘{{/success}} {{ uppercasefirst build.status }}: Build #{{ build.number }}* (type: `{{ build.event }}`)
      <{{ build.link }}|Visit build page ↗>
      {{/success}}
      Commit: <https://github.com/{{ repo.owner }}/{{ repo.name }}/commit/{{ build.commit }}|{{ truncate build.commit 8 }}> 

      Branch: <https://github.com/{{ repo.owner }}/{{ repo.name }}/commits/{{ build.branch }}|{{ build.branch }}> 

      Author: {{ build.author }} 
  when:
    status:
      - success
      - failure
```
